[build]
    command = "CI= npm run build"

[[redirects]]
    from = "/*"
    to="/index.html"
    status=200

[[plugins]]
package = "netlify-plugin-ttl-cache"
  [plugins.inputs]
  path = "build"
  ttl = 90